//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soulbrain.BarcodeMan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soulbrain.BarcodeMan.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 협력사 원자재 관리시스템.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택.
        /// </summary>
        public static string Barcode_Check {
            get {
                return ResourceManager.GetString("Barcode_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유효기간.
        /// </summary>
        public static string Barcode_ExpDate {
            get {
                return ResourceManager.GetString("Barcode_ExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유효기간 선택해주세요..
        /// </summary>
        public static string Barcode_ExpiryDateRequired {
            get {
                return ResourceManager.GetString("Barcode_ExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string Barcode_LotNo {
            get {
                return ResourceManager.GetString("Barcode_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo가 빠졌습니다..
        /// </summary>
        public static string Barcode_LotNoRequired {
            get {
                return ResourceManager.GetString("Barcode_LotNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제조일.
        /// </summary>
        public static string Barcode_ManufacDate {
            get {
                return ResourceManager.GetString("Barcode_ManufacDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 포장수량.
        /// </summary>
        public static string Barcode_PackingAmt {
            get {
                return ResourceManager.GetString("Barcode_PackingAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발행일시.
        /// </summary>
        public static string Barcode_PrintDate {
            get {
                return ResourceManager.GetString("Barcode_PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발행수량.
        /// </summary>
        public static string Barcode_PrintQty {
            get {
                return ResourceManager.GetString("Barcode_PrintQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 출력양식.
        /// </summary>
        public static string Barcode_PrintType {
            get {
                return ResourceManager.GetString("Barcode_PrintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제조일 입력해 주세요..
        /// </summary>
        public static string Barcode_ProductDateRequired {
            get {
                return ResourceManager.GetString("Barcode_ProductDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공급수량.
        /// </summary>
        public static string Barcode_SupplyAmt {
            get {
                return ResourceManager.GetString("Barcode_SupplyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공급일.
        /// </summary>
        public static string Barcode_SupplyDate {
            get {
                return ResourceManager.GetString("Barcode_SupplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공급일 입력해주세요..
        /// </summary>
        public static string Barcode_SupplyDateRequired {
            get {
                return ResourceManager.GetString("Barcode_SupplyDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공급수량이 빠졌습니다..
        /// </summary>
        public static string Barcode_SupplyQtyRequired {
            get {
                return ResourceManager.GetString("Barcode_SupplyQtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품목추가.
        /// </summary>
        public static string Button_AddProducts {
            get {
                return ResourceManager.GetString("Button_AddProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행 추가.
        /// </summary>
        public static string Button_AddRow {
            get {
                return ResourceManager.GetString("Button_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행 삭제.
        /// </summary>
        public static string Button_DeleteRow {
            get {
                return ResourceManager.GetString("Button_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수정.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품목찾기.
        /// </summary>
        public static string Button_FindProducts {
            get {
                return ResourceManager.GetString("Button_FindProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 목록.
        /// </summary>
        public static string Button_List {
            get {
                return ResourceManager.GetString("Button_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바코드라벨 출력.
        /// </summary>
        public static string Button_PrintBarcodeLabel {
            get {
                return ResourceManager.GetString("Button_PrintBarcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현품표 출력.
        /// </summary>
        public static string Button_PrintStockTable {
            get {
                return ResourceManager.GetString("Button_PrintStockTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재발행.
        /// </summary>
        public static string Button_RePrint {
            get {
                return ResourceManager.GetString("Button_RePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조회.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 댓글내용.
        /// </summary>
        public static string Comment_Content {
            get {
                return ResourceManager.GetString("Comment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성일시.
        /// </summary>
        public static string Comment_CreatedDate {
            get {
                return ResourceManager.GetString("Comment_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성자.
        /// </summary>
        public static string Comment_Creator {
            get {
                return ResourceManager.GetString("Comment_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비고.
        /// </summary>
        public static string File_Note {
            get {
                return ResourceManager.GetString("File_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일반공지.
        /// </summary>
        public static string Label_General {
            get {
                return ResourceManager.GetString("Label_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중요공지.
        /// </summary>
        public static string Label_Important {
            get {
                return ResourceManager.GetString("Label_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 페이지 수.
        /// </summary>
        public static string Label_PageSize {
            get {
                return ResourceManager.GetString("Label_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디 기억.
        /// </summary>
        public static string Login_RememberID {
            get {
                return ResourceManager.GetString("Login_RememberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디.
        /// </summary>
        public static string Login_UserID {
            get {
                return ResourceManager.GetString("Login_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바코드 발행 등록.
        /// </summary>
        public static string Page_BarcodePrint {
            get {
                return ResourceManager.GetString("Page_BarcodePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바코드 발행 이력.
        /// </summary>
        public static string Page_BarcodePrintList {
            get {
                return ResourceManager.GetString("Page_BarcodePrintList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호변경.
        /// </summary>
        public static string Page_ChangePassword {
            get {
                return ResourceManager.GetString("Page_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 홈.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그아웃.
        /// </summary>
        public static string Page_Logout {
            get {
                return ResourceManager.GetString("Page_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공지사항.
        /// </summary>
        public static string Page_Notice {
            get {
                return ResourceManager.GetString("Page_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제품정보.
        /// </summary>
        public static string Page_ProductInfo {
            get {
                return ResourceManager.GetString("Page_ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업무게시판.
        /// </summary>
        public static string Page_TaskBoard {
            get {
                return ResourceManager.GetString("Page_TaskBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제품코드.
        /// </summary>
        public static string Product_ItemCode {
            get {
                return ResourceManager.GetString("Product_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제품명.
        /// </summary>
        public static string Product_ItemName {
            get {
                return ResourceManager.GetString("Product_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자재그룹.
        /// </summary>
        public static string Product_MaterialGroup {
            get {
                return ResourceManager.GetString("Product_MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자재유형.
        /// </summary>
        public static string Product_MaterialType {
            get {
                return ResourceManager.GetString("Product_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 단위.
        /// </summary>
        public static string Product_Unit {
            get {
                return ResourceManager.GetString("Product_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호 확인.
        /// </summary>
        public static string PW_ConfirmPassword {
            get {
                return ResourceManager.GetString("PW_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 비밀번호.
        /// </summary>
        public static string PW_CurrentPassword {
            get {
                return ResourceManager.GetString("PW_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 비밀번호가 맞지 않습니다..
        /// </summary>
        public static string PW_MSG_InvalidPW {
            get {
                return ResourceManager.GetString("PW_MSG_InvalidPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호가 변경되엇습니다..
        /// </summary>
        public static string PW_MSG_PWChanged {
            get {
                return ResourceManager.GetString("PW_MSG_PWChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 정확히 반복하세요..
        /// </summary>
        public static string PW_MSG_RepeatPWCorrectly {
            get {
                return ResourceManager.GetString("PW_MSG_RepeatPWCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새 비밀번호.
        /// </summary>
        public static string PW_NewPassword {
            get {
                return ResourceManager.GetString("PW_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체.
        /// </summary>
        public static string Text_All {
            get {
                return ResourceManager.GetString("Text_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바코드라벨.
        /// </summary>
        public static string Text_BarcodeLabel {
            get {
                return ResourceManager.GetString("Text_BarcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 개월.
        /// </summary>
        public static string Text_ExpDateValue {
            get {
                return ResourceManager.GetString("Text_ExpDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택항목이 없습니다..
        /// </summary>
        public static string Text_NoSelection {
            get {
                return ResourceManager.GetString("Text_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택.
        /// </summary>
        public static string Text_Select {
            get {
                return ResourceManager.GetString("Text_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현품표.
        /// </summary>
        public static string Text_StockTable {
            get {
                return ResourceManager.GetString("Text_StockTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 페이지는 유지 보수 중입니다..
        /// </summary>
        public static string TEXT_ThisPageIsUnderMaintenance {
            get {
                return ResourceManager.GetString("TEXT_ThisPageIsUnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 항목들을 삭제하시겠습니까?.
        /// </summary>
        public static string WebBarCode_ConfirmDelete {
            get {
                return ResourceManager.GetString("WebBarCode_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첨부파일.
        /// </summary>
        public static string WebBoard_AttachFile {
            get {
                return ResourceManager.GetString("WebBoard_AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 게시물 번호.
        /// </summary>
        public static string WebBoard_BoardID {
            get {
                return ResourceManager.GetString("WebBoard_BoardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 댓글.
        /// </summary>
        public static string WebBoard_Comment {
            get {
                return ResourceManager.GetString("WebBoard_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 댓글수.
        /// </summary>
        public static string WebBoard_Comments {
            get {
                return ResourceManager.GetString("WebBoard_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내용.
        /// </summary>
        public static string WebBoard_Contents {
            get {
                return ResourceManager.GetString("WebBoard_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성일.
        /// </summary>
        public static string WebBoard_CreatedDate {
            get {
                return ResourceManager.GetString("WebBoard_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성자.
        /// </summary>
        public static string WebBoard_Creator {
            get {
                return ResourceManager.GetString("WebBoard_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중요.
        /// </summary>
        public static string WebBoard_Mark {
            get {
                return ResourceManager.GetString("WebBoard_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제목.
        /// </summary>
        public static string WebBoard_Title {
            get {
                return ResourceManager.GetString("WebBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첨부파일.
        /// </summary>
        public static string WebNotice_AttachFile {
            get {
                return ResourceManager.GetString("WebNotice_AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내용.
        /// </summary>
        public static string WebNotice_Contents {
            get {
                return ResourceManager.GetString("WebNotice_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성일.
        /// </summary>
        public static string WebNotice_CreatedDate {
            get {
                return ResourceManager.GetString("WebNotice_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작성자.
        /// </summary>
        public static string WebNotice_Creator {
            get {
                return ResourceManager.GetString("WebNotice_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중요.
        /// </summary>
        public static string WebNotice_Mark {
            get {
                return ResourceManager.GetString("WebNotice_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제목.
        /// </summary>
        public static string WebNotice_Title {
            get {
                return ResourceManager.GetString("WebNotice_Title", resourceCulture);
            }
        }
    }
}
