using Soulbrain.BarcodeMan.Domain;
using Soulbrain.BarcodeMan.EntityFramework;
using Soulbrain.BarcodeMan.Enums;
using System.Collections.Generic;
using System.Data.Entity.Migrations;

namespace Soulbrain.BarcodeMan.Migrations.SeedData
{
    public class ProductsCreator
    {
        private readonly AppDbContext _context;

        public ProductsCreator(AppDbContext context)
        {
            _context = context;
        }

        public void Create()
        {

            var products = new List<Product>
            {
                new Product { PlantCode = "1100", ProductCode = "40000001", ProductName = @"TEOS,Drum,99.99%,LB", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000002", ProductName = @"TMOP,Drum,99.9%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000003", ProductName = @"TMB,Drum,99.7%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000004", ProductName = @"TMPI,Drum,99.7%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000005", ProductName = @"POCl3,Can,98%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000006", ProductName = @"TEB,Drum,99.7%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000008", ProductName = @"TEPO,Drum,99.7%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000010", ProductName = @"BBr3,Can,99.999%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000011", ProductName = @"TiCl4,Drum,99%", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000014", ProductName = @"TG 질산,Tank Lorry,71%(공주)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000015", ProductName = @"Oxalic Acid,Bag,97%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000018", ProductName = @"HCl,Drum,35%,LCD", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000020", ProductName = @"PCA(Perchloric Acid), Drum,70%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000021", ProductName = @"HF,50%,Tank Lorry, 공정2팀", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000022", ProductName = @"Surfactant,FT612R", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000023", ProductName = @"Aac,Bag,97%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000024", ProductName = @"Ap2,Bag,98%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000025", ProductName = @"Sulfuric Acid,Bottle,96%,전자급", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000026", ProductName = @"KOH,Drum,48%(공정3팀),전자급", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000027", ProductName = @"Reolosil,Bag,", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000028", ProductName = @"IPA,Bottle,99%", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000029", ProductName = @"Glycerine,Bottle,99%", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000031", ProductName = @"VC(Vinylenecarbonate,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000032", ProductName = @"BP(Biphenyl,Bottle,98%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000033", ProductName = @"PS(1,3-Propanesultone,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000034", ProductName = @"CHB(Cyclohexylbenzene,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000036", ProductName = @"PC(Propylenecarbonate,Drum,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000037", ProductName = @"DMC(Dimethylcarbonate,Drum,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000038", ProductName = @"DEC(Diehtylcarbonate,Drum,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000039", ProductName = @"EMC(Ethylmethylcarbonate,Drum,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000040", ProductName = @"GBL, Drum, 99.7%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000041", ProductName = @"LiBOB(Lithiumbis(oxaleto)borate,Bottle)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000042", ProductName = @"LiBF4(Lithiumtetrafluoroborate,Bottle)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000044", ProductName = @"TBEP, Drum, 94%(삭제)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000046", ProductName = @"SN(Succinonitrile,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000055", ProductName = @"NH4F,40%,공정2팀", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000056", ProductName = @"Copper Sulfate,Bag,98%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000060", ProductName = @"4Cl-Toluene,Drum,99%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000061", ProductName = @"H2O2,Tank Lorry,35%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000062", ProductName = @"IDA,Bag,99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000063", ProductName = @"5-Aminotetrazole,Bag,99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000064", ProductName = @"KHSO4,Bag,99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000065", ProductName = @"AP,Bag,98%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000068", ProductName = @"EG,Drum,98%(미사용)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000069", ProductName = @"TGME,Drum,99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000070", ProductName = @"Ethylamine,GLASS,70%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000071", ProductName = @"H2O2,BOTTLE,31%,전자급", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000072", ProductName = @"Hydrazine,Drum,80%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000073", ProductName = @"BTA,Bag,99.9%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000074", ProductName = @"BA,Glass,99.5%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000075", ProductName = @"Glycine,CAN,99%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000076", ProductName = @"HF,50%,장항", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000078", ProductName = @"CH3COOH,Tank Lorry,99.85%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000079", ProductName = @"H3PO4,Tank Lorry,85%,LCD", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000080", ProductName = @"FEC(Fluoroethylenecarbonate,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000081", ProductName = @"TEABF4,Bottle,99.9%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000082", ProductName = @"NMP,Drum,99.85%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000083", ProductName = @"CH3COOH,Bottle,99.9%,전자급", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000084", ProductName = @"LiTFSi", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000085", ProductName = @"DME,DRUM,99.9%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000087", ProductName = @"THF,DRUM,99.9%(삭제)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000088", ProductName = @"TPL-155,DRUM,99.9%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000089", ProductName = @"VEC(Vinylethylenecarbonate,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000092", ProductName = @"HF,Drum,50%,파주", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000093", ProductName = @"Methyl Gallate,bag,99.9%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000097", ProductName = @"Ammonium Nitrate,bag,99%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000099", ProductName = @"Ethyl Alcohol,bottle,99.9%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000100", ProductName = @"Ethyl Amine,Bottle,70%(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000110", ProductName = @"Imidazole,bag,99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000122", ProductName = @"HNO3,Drum,71%,LCD(공주)-(동우)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000123", ProductName = @"Zinc Actate, bag, 99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000124", ProductName = @"KOH,Drum,45%(공정2팀)(삭제)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000125", ProductName = @"Pyrogallol,Drum,99.8%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000130", ProductName = @"KOH,Drum,45%(Cr Etchant팀)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000160", ProductName = @"EG,Tank Lorry,99.99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000172", ProductName = @"SNE(SN+EMC,Cyl)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000180", ProductName = @"EC(Ethylene Carbonate,99.9%,T/L,KL)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000181", ProductName = @"LiPF6,후성,99%", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000183", ProductName = @"Glycine,Bottle,99%,Junsei", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000184", ProductName = @"Methanol,Bottle,99%,DSP", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000190", ProductName = @"1M,Bottle,99.9%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000191", ProductName = @"ACl,Bag,99.9%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000193", ProductName = @"NCA,Bag,99.9%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000194", ProductName = @"BDG, Drum, 99.8%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000201", ProductName = @"Ammonium Citrate, 20kg/Bag99.8%", MaterialGroupCode = "L10", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000210", ProductName = @"Ammonia Water, 18kg, 29%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000211", ProductName = @"PST(Prop-1-ene-1,3-sultone,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000212", ProductName = @"KA,Bag,99%,중국산", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000213", ProductName = @"Aerosil 90S,Bag,Degussa(삭제)", MaterialGroupCode = "L03", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000220", ProductName = @"DEZ", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000221", ProductName = @"4-FT(4-Fluorotoluene,Cyl,99.9%)", MaterialGroupCode = "L06", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000225", ProductName = @"TMA, TCLC,2406g,SUS", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000226", ProductName = @"TEMAHf, Aldrich,SUS", MaterialGroupCode = "L01", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000238", ProductName = @"EC(Ethyl Cellosolve),99%", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000239", ProductName = @"Pyrogallol Solution", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000240", ProductName = @"PAA(40K)", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000241", ProductName = @"85% H3PO4,EL-1,300kg,KD,SS", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000242", ProductName = @"Triethanolamine", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
                new Product { PlantCode = "1100", ProductCode = "40000243", ProductName = @"Citric Acid", MaterialGroupCode = "L02", MaterialTypeCode = "ROH", InspectFlag = StrBool.True, BaseUnitCode = UnitCode.Kilogram, UseFlag = StrBool.True },
            };

            products.ForEach(s => _context.Products.AddOrUpdate(s));
            _context.SaveChanges();
        }
    }
}
