// <auto-generated />
namespace Soulbrain.BarcodeMan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_Fields_Fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_Fields_Fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201812130829522_DB_Fields_Fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
